### ISSUE TITLE
'str' type is not supported as a pyqtSignal() type

### ISSUE THREAD

**Issue by ghost** [robertbasic/ape#1]
Traceback:
    File "/home/linuxhun/ape/src/apelib/elements.py", line 76, in apeNewFileDialog
      fileCreated = pyqtSignal('str')
    TypeError: type 'str' is not supported as a pyqtSignal() type argument type

You can correct it, by replacing 'str' with str. Example:
    pyqtSignal(str)

P.s.: I'm using Qt 4.7, with PyQt 4.7.4

**Comment by robertbasic** [comment]
Pushed the fix.

Thanks for the report! :)
