### ISSUE TITLE
Option to use a monospaced font

### ISSUE THREAD

**Issue by asgrim** [robertbasic/ape#2]
I can't stand using proportional fonts for editing stuff, it would be nice to at least have the option to change the font to a monospace font, although the best solution in my opinion would be to have a standard font chooser to allow you to pick any font installed.

**Comment by asgrim** [comment]
@robertbasic did you know that this was my first issue on GitHub? :smile:

**Comment by robertbasic** [comment]
@asgrim 😹 it's been a while, maybe I should do something about it :D
